[package]
name = "ecdsa0-methods"
version = "0.1.0"
edition = "2021"

[dependencies]


[build-dependencies]
risc0-build = { git = "https://github.com/l2iterative/risc0/", branch="no-rust-runtime-for-host" }

[package.metadata.risc0]
methods = ["guest"]